name = "Memoize"
uuid = "c03570c3-d221-55d1-a50c-7939bbd78826"
authors = ["Simon Kornblith <simon@simonster.com>",
           "CÃ©dric St-Jean <cedric.stjean@gmail.com>",
           "Kevin Squire <kevin.squire@gmail.com",
           "Contributors (https://github.com/JuliaCollections/Memoize.jl/graphs/contributors)"]
version = "0.5.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "~0.4, ~0.5"
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
